title: PauloPath
email: paulopath@gmail.com
description: >- 
  Developer self organizing docs
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: paulopath

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
